use_frameworks!

platform :ios, '8.0'

target 'MediatorOilCategory_Example' do
  pod 'MediatorOilCategory', :path => '../'
  pod 'CTMediator'
  target 'MediatorOilCategory_Tests' do
    inherit! :search_paths

    
  end
end
